import type { Plan } from "@/types";

export const seedPlans: Plan[] = [
  {
    id: "plan-101",
    creator: "Alex",
    creatorId: null,
    title: "BIOL 1009 Exam Review",
    category: "Study",
    description: "Review ecology concepts and work through practice questions before the exam.",
    interests: [],
    courses: ["BIOL 1009"],
    location: "Walter Library",
    startsAt: "Tonight · 7:00 PM",
    startsAtIso: null,
    duration: "2 hours",
    maxPeople: 5,
    currentMembers: 3,
    matchScore: 92,
    reasons: ["Same course", "Strong time overlap", "Prefers small study groups"],
    members: ["Alex", "Sarah", "Kevin"],
    memberIds: [],
    externalEvent: null,
  },
  {
    id: "plan-102",
    creator: "Maya",
    creatorId: null,
    title: "Pickup Basketball",
    category: "Sports",
    description: "Casual pickup basketball. Any skill level is welcome.",
    interests: ["Basketball"],
    courses: [],
    location: "RecWell",
    startsAt: "Saturday · 3:00 PM",
    startsAtIso: null,
    duration: "90 minutes",
    maxPeople: 8,
    currentMembers: 5,
    matchScore: 86,
    reasons: ["Available at the same time", "Sports interest overlap", "Group size fits"],
    members: ["Maya", "Jordan", "Leo", "Emma", "Chris"],
    memberIds: [],
    externalEvent: null,
  },
  {
    id: "plan-103",
    creator: "Nina",
    creatorId: null,
    title: "Campus Photography Walk",
    category: "Others",
    description: "Take photos around campus and share composition tips. Any camera is welcome.",
    interests: ["Photography"],
    courses: [],
    location: "Northrop Mall",
    startsAt: "Friday · 6:30 PM",
    startsAtIso: null,
    duration: "3 hours",
    maxPeople: 4,
    currentMembers: 2,
    matchScore: 89,
    reasons: ["Shared creative interest", "Availability overlap", "Group size fits"],
    members: ["Nina", "Owen"],
    memberIds: [],
    externalEvent: null,
  },
];
